### PR TITLE
Saml2 auth handler/upgrade sling12 open samlv4 java11

### PR DESCRIPTION
**Pull request by cmrockwell**
Upgraded SAML2 Handler to OpenSAML V4. Java 11. Sling 12. 
OpenSAML V4 is not compatible with Java 8.

Reviewed and optimized embedded OpenSAML dependencies and updated versions.

Made encryption and signing an optional configuration

Added logout URL config used after dropping credentials. User is redirected to the URL configured.

Added error handling (runtime exception) if the userID is not configured properly. 
JCR Group ID's now seem to have a slash in front. Added condition to allow that. 

Updated realm-sling-export.json (for Keycloak demo) adding attribute mappers for client, http://localhost:8080

Added src/main/resources/localhostExample-1.zip package

Updated README

### CODE REVIEW

**Comment by cmrockwell** [comment]
How important is continued use of Java 8 for this bundle? 
Maybe there could be a CI pipeline for Java 11?

https://builds.apache.org/blue/organizations/jenkins/Sling%2Fsling-whiteboard/detail/PR-60/2/pipeline

**Comment by rombert** [comment]
We could try switching the whole build to JDK 11. The thing is we only have one project, and that's the whiteboard rector. Can you try running `mvn clean verify` in the root of the Sling Whiteboard as see if all projects build?

**Comment by cmrockwell** [comment]
Running `mvn clean verify` at the parent works for me...

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Sling - Maven Central Source Reporter 0.0.1-SNAPSHOT SUCCESS [ 12.467 s]
[INFO] Sling Model Persistor 1.0-SNAPSHOT ................. SUCCESS [  3.799 s]
[INFO] Apache Sling Starter Content System Information 1.0-SNAPSHOT SUCCESS [  0.942 s]
[INFO] Apache Sling Commons Prometheus Metrics Exporter 1.0-SNAPSHOT SUCCESS [  0.820 s]
[INFO] SAML2 Service Provider 0.2.0-SNAPSHOT .............. SUCCESS [  7.003 s]
[INFO] Apache Sling Whiteboard (Builder) 1 ................ SUCCESS [  0.827 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.377 s
[INFO] Finished at: 2020-06-23T12:03:40-04:00
[INFO] ------------------------------------------------------------------------
➜  sling-whiteboard git:(saml2-auth-handler/Upgrade-Sling12-OpenSAMLV4-Java11)

**Comment by rombert** [comment]
@cmrockwell - I've switched the Jenkins build to Java 11 with https://github.com/apache/sling-whiteboard/pull/61 . Please rebase on top of that, the build should be fine now.

**Comment by cmrockwell** [comment]
I'm going to close #60 and try the build again with #61

**Pull request closed without merging**
